#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# rainloop php files
if [[ ! -d /config/www/rainloop ]]; then
    echo 'extract rainloop server files'
    mkdir -p /config/www/rainloop
    cp -R /rainloop /config/www/rainloop
fi
